const GET_COURSES = 'GET_COURSES';
const GET_COURSES_FULFILLED = 'GET_COURSES_FULFILLED';
const GET_COURSES_REJECTED = 'GET_COURSES_REJECTED';

const CREATE_COURSE = 'CREATE_COURSE';
const CREATE_COURSE_FULFILLED = 'CREATE_COURSE_FULFILLED';
const CREATE_COURSE_REJECTED = 'CREATE_COURSE_REJECTED';

const DELETE_COURSE = 'DELETE_COURSE';
const DELETE_COURSE_FULFILLED = 'DELETE_COURSE_FULFILLED';
const DELETE_COURSE_REJECTED = 'DELETE_COURSE_REJECTED';

const DUPLICATE_COURSE = 'DUPLICATE_COURSE';
const DUPLICATE_COURSE_FULFILLED = 'DUPLICATE_COURSE_FULFILLED';
const DUPLICATE_COURSE_REJECTED = 'DUPLICATE_COURSE_REJECTED';

export {
  GET_COURSES,
  GET_COURSES_FULFILLED,
  GET_COURSES_REJECTED,
  CREATE_COURSE,
  CREATE_COURSE_FULFILLED,
  CREATE_COURSE_REJECTED,
  DELETE_COURSE,
  DELETE_COURSE_FULFILLED,
  DELETE_COURSE_REJECTED,
  DUPLICATE_COURSE,
  DUPLICATE_COURSE_FULFILLED,
  DUPLICATE_COURSE_REJECTED,
};
