const GET_LESSON = 'GET_LESSON';
const GET_LESSON_FULFILLED = 'GET_LESSON_FULFILLED';
const GET_LESSON_REJECTED = 'GET_LESSON_REJECTED';

export {
  GET_LESSON,
  GET_LESSON_FULFILLED,
  GET_LESSON_REJECTED,
};
